# Generated by Django 5.0.7 on 2024-07-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
